package myClasses;
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.03.31 at 04:03:56 PM IDT
//

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}rse-stocks"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "rizpa-stock-exchange-descriptor")
public class RizpaStockExchangeDescriptor {

    @XmlElement(name = "rse-stocks", required = true)
    protected RseStocks rseStocks;

    public RizpaStockExchangeDescriptor(InputStream in)throws JAXBException{
            rseStocks = deserializeFrom(in);
    }
    public RizpaStockExchangeDescriptor(){}

    /**
     * Gets the value of the rseStocks property.
     *
     * @return possible object is
     * {@link RseStocks }
     */
    public RseStocks getRseStocks() {
        return rseStocks;
    }
    /**
     * Sets the value of the rseStocks property.
     *
     * @param value allowed object is
     *              {@link RseStocks }
     */
    public void setRseStocks(RseStocks value) {
        rseStocks = value;
    }

    //
    public String checkRSED() {
        List<RseStock> lst = new ArrayList<RseStock>();

        for (RseStock r : rseStocks.getRseStock()) {
            for (RseStock s : lst) {
                if (r.getRseSymbol().equalsIgnoreCase(s.getRseSymbol()))
                    return "2 or more companies have same symbol";
                if (r.getRseCompanyName().equalsIgnoreCase(s.getRseCompanyName()))
                    return "company appears on 2 or more stocks";
            }
            lst.add(r);
        }
        return null;
    }

    public RseStock findStock(String str) {
        for (RseStock r : getRseStocks().getRseStock()) {
            if (r.getRseSymbol().equalsIgnoreCase(str)) {
                return r;
            }
        }
        return null;
    }

    public RseStocks deserializeFrom(InputStream in) throws JAXBException {
        JAXBContext jc = JAXBContext.newInstance("myClasses");
        Unmarshaller u = jc.createUnmarshaller();
        return ((RizpaStockExchangeDescriptor) u.unmarshal(in)).rseStocks;
    }
}
